### ISSUE TITLE
Build pkg package for macOS

### ISSUE THREAD

**Issue by mfroembgen** [florianklueckmann/LATIC#57]
Please provide a pkg package as an additional release for macOS users of LATIC.

 Basic example: 
`jpackage --name LATIC --input . --main-jar LATIC-1.2.1.jar --type pkg`

Additional it makes sense to update the documentation for macOS afterwards. As I guess that you are not a verified apple developer you need to put some additional information into the documentation on how to install packages from unverified developers. (https://support.apple.com/de-de/guide/mac-help/mh40616/mac)

**Comment by florianklueckmann** [comment]
Thank you for the suggestion. 
Unfortunately, I do not own a macOS device and therefore can't bundle the application for macOS. 

However, I will look into the GitHub macOS runners.

**Comment by mfroembgen** [comment]
Good job! I have seen that you've got it working.
